#!/bin/sh

# Ensure we use the appropriate gtkrc-2.0 file
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# We do not want to rely on crappy mailcap
# export MAILCAPS="$HOME/.mailcap"

# Make QT automatically scale according to screen DPI
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME=qt5ct

# GTK3 apps try to contact org.a11y.Bus. Disable that.
export NO_AT_BRIDGE=1

# Environment variables
. "$HOME/.zshenv"
export TERMINAL=kitty

dconf <"$HOME/.config/i3/dotfiles/dconf.ini" load /

# Services are started with systemd
systemctl --user import-environment
systemctl --user daemon-reload
exec systemctl --user start --wait i3-session.target
